services:
  petcare_db:
    image: postgres:17
    container_name: petcare_db
    environment:
      POSTGRES_DB: petcare
      POSTGRES_USER: petcare
      POSTGRES_PASSWORD: petcare
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - petcare-net

  petcare:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petcare
    environment:
      JWT_SECRET_BASE64: 598c0e890a71a89f6f02ba07e03cb18dbad8c3e327d3cc5b390fc37a357b5d90
    restart: unless-stopped
    depends_on:
      - petcare_db
    ports:
      - "8080:8080"
    networks:
      - petcare-net

volumes:
  pgdata:

networks:
  petcare-net:
    driver: bridge
